version: "3.8"

services:
  web:
    container_name: web
    build: .
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://${MONGO_ROOT_USER:-root}:${MONGO_ROOT_PASSWORD:-admin}@mongo:27017
      MONGO_DB_NAME: ${MONGO_DB_NAME:-todo}
    volumes:
      - .:/app
    networks:
      - main
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: on-failure
    volumes:
      - ./db/mongo:/data/db
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-todo}
    networks:
      - main

volumes:
  mongo: {}
networks:
  main: {}
